#!/usr/bin/env bash

STAGED_PHP_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".php\{0,1\}$")
PASS=true
if [[ "$STAGED_PHP_FILES" = "" ]]; then
  echo -e "${LIGHT_GREEN}No PHP files staged\n${NO_COLOR}"
fi

if [[ "$STAGED_PHP_FILES" != "" ]]; then
	if make tests; then
		exit 0
	else
		exit 1
	fi
f