stages:
  - image:build
  - tests
  - statistics

variables:
    PHP_IMAGE:                  ${DOCKER_REGISTRY_INTERNAL}/${CI_PROJECT_PATH_SLUG}/php:${CI_COMMIT_SHA}
    PHP_IMAGE_CACHE:            ${DOCKER_REGISTRY_INTERNAL}/${CI_PROJECT_PATH_SLUG}/php:cache

buildkit:
  stage: image:build
  image: ${BUILDKIT_IMAGE}
  timeout: 5m
  script:
    - ${BUILDKIT_SCRIPT}
      --tag=${PHP_IMAGE}
      --cache-repo=${PHP_IMAGE_CACHE}
      --context=.
      --file=./images/php/pipeline/Dockerfile

unit tests:
  stage: tests
  image: ${PHP_IMAGE}
  timeout: 5m
  script:
    - cp -av /var/www/vendor ./vendor
    - vendor/bin/phpunit --colors=always -c tests/phpunit.xml

phpstan:
  stage: tests
  image: ${PHP_IMAGE}
  timeout: 5m
  script:
    - /var/www/vendor/bin/phpstan analyse ./src ./tests -l 8

code sniffer:
  stage: tests
  image: ${PHP_IMAGE}
  timeout: 5m
  script:
    - /var/www/vendor/bin/phpcs src/ tests/ --standard=./config/codesniffer_ruleset.xml

statistics:
  stage: statistics
  image: ${PHP_IMAGE}
  timeout: 5m
  only:
    - main
  script:
    - bin/workflow workflow:deployment:statistics:update
