version: '3'
services:
  php:
    image: php:7.4-fpm
    working_dir: /var/www
    volumes:
      - ./:/var/www:delegated

  composer:
    image: composer:latest
    command: install -o
    volumes:
      - .:/app:delegated
