version: '3'
services:
  php:
      build:
          context: ./docker/
          dockerfile: Dockerfile
      tty: true
      stdin_open: true
      volumes:
        - ./:/var/www:delegated
  composer:
    image: composer:latest
    command: install -o --ignore-platform-reqs
    volumes:
      - .:/app:delegated
