version: '3'
services:
  php:
    build:
      context: images/php
    working_dir: /var/www
    env_file:
      - .env
    volumes:
      - ./:/var/www:delegated
      - ~/.ssh:/home/${UNAME}/.ssh
    tty: true
    stdin_open: true

  composer:
    image: composer:latest
    command: install -o --ignore-platform-reqs
    volumes:
      - .:/app:delegated
