version: '3'
services:
  php:
    build:
      context: images/php
    working_dir: /var/www
    env_file:
      - .env
    volumes:
      - ./:/var/www:delegated

  composer:
    image: composer:latest
    command: install -o
    volumes:
      - .:/app:delegated
